const GET_GAMES = 'GET_GAMES'
const GET_DETAILS = 'GET_DETAILS'
const GET_GENRES = 'GET_GENRES'
const ORDEN_SORT = 'ORDEN_SORT'
const FILTER_GENRES = 'FILTER_GENRES'
const GAME_SEARCH = 'GAME_SEARCH'

export {GET_GAMES,GET_DETAILS,GET_GENRES,ORDEN_SORT,FILTER_GENRES,GAME_SEARCH}